---
Name: admin-branding
Before:
  - '#login-forms'
---
SilverStripe\LoginForms\EnablerExtension:
  login_themes:
    # insert before themes in vendor/silverstripe/login-forms/_config/theme.yml
    - 'restruct/silverstripe-login-branding:login-forms'

SilverStripe\Security\Security:
  extensions:
    - 'Restruct\SilverStripe\AdminBranding\SecurityBrandingExtension'
